# autogenerated
cards = [
    {'id': 295517, 'name': 'A Legendary Ocean', 'alias': 22702055, 'releasedate': '2003-06-06'},
    {'id': 91932350, 'name': 'Harpie Lady 1', 'alias': 76812113, 'releasedate': '2004-11-20'},
    {'id': 27927359, 'name': 'Harpie Lady 2', 'alias': 76812113, 'releasedate': '2004-11-20'},
    {'id': 54415063, 'name': 'Harpie Lady 3', 'alias': 76812113, 'releasedate': '2004-11-20'},
    {'id': 80316585, 'name': 'Cyber Harpie Lady', 'alias': 76812113, 'releasedate': '2005-02-26'},
    {'id': 78734254, 'name': 'Neo-Spacian Marine Dolphin', 'alias': 17955766, 'releasedate': '2007-08-15'},
    {'id': 13857930, 'name': 'Neo-Spacian Twinkle Moss', 'alias': 17732278, 'releasedate': '2008-01-26'},
    {'id': 34103656, 'name': 'Lemuria, the Forgotten City', 'alias': 22702055, 'releasedate': '2012-11-09'},
    {'id': 74335036, 'name': 'Fusion Substitute', 'alias': 24094653, 'releasedate': '2014-11-06'},
    {'id': 2819435, 'name': 'Pacifis, the Phantasm City', 'alias': 22702055, 'releasedate': '2017-05-04'},
    {'id': 26534688, 'name': 'Magellanica, the Deep Sea City', 'alias': 22702055, 'releasedate': '2020-08-06'},
    {'id': 75402014, 'name': 'Ultimate Dragonic Utopia Ray', 'alias': 56840427, 'releasedate': '2021-06-03'},
    {'id': 68679595, 'name': 'Ultimate Leo Utopia Ray', 'alias': 56840427, 'releasedate': '2021-12-02'},
]
